name: Build binary

on:
    release:
        types: [created]

jobs:
    windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Install dependencies
              run: yarn install

            - name: Build Binary
              run: yarn build

            - name: Create Release
              id: create_release
              uses: shogo82148/actions-create-release@v1

            - uses: shogo82148/actions-upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: nexus.exe
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Install dependencies
              run: yarn install

            - name: Build Binary
              run: yarn build

            - name: Create Release
              id: create_release
              uses: shogo82148/actions-create-release@v1

            - uses: shogo82148/actions-upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: nexus
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    mac:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Install dependencies
              run: yarn install

            - name: Build Binary
              run: yarn build

            - name: Create Release
              id: create_release
              uses: shogo82148/actions-create-release@v1

            - uses: shogo82148/actions-upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: nexus.exe
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
